keywords = {'FINANCE': ['FINANCE',
             'ACCOUNTING',
             'INVESTMENT',
             'BANKING',
             'FINANCIAL ANALYSIS',
             'RISK MANAGEMENT',
             'ASSET MANAGEMENT',
             'PORTFOLIO MANAGEMENT',
             'FINANCIAL PLANNING',
             'BUDGETING',
             'TAXATION',
             'AUDITING',
             'FINANCIAL REPORTING',
             'CORPORATE FINANCE',
             'FINANCIAL MODELING',
             'MERGERS AND ACQUISITIONS',
             'HEDGE FUNDS',
             'EQUITY RESEARCH',
             'TREASURY',
             'INSURANCE'],
 'GRAPHIC DESIGN': ['GRAPHIC DESIGN',
                    'VISUAL DESIGN',
                    'ART DIRECTION',
                    'ILLUSTRATION',
                    'LOGO DESIGN',
                    'TYPOGRAPHY',
                    'LAYOUT',
                    'BRANDING',
                    'USER INTERFACE DESIGN',
                    'USER EXPERIENCE DESIGN',
                    'PRINT DESIGN',
                    'DIGITAL DESIGN',
                    'PACKAGING DESIGN',
                    'MOTION GRAPHICS',
                    'INFOGRAPHICS',
                    'WEB DESIGN',
                    'MARKETING DESIGN',
                    'ADVERTISING DESIGN',
                    'PUBLICATION DESIGN',
                    'CREATIVE DIRECTION'],
 'INTERNSHIP': ['APPRENTICESHIP',
                'TRAINEESHIP',
                'PLACEMENT',
                'EXTERNSHIP',
                'RESIDENCY',
                'FELLOWSHIP',
                'WORK EXPERIENCE',
                'CO-OP',
                'PRACTICUM',
                'ATTACHMENT',
                'JOB SHADOWING',
                'VOLUNTEERISM',
                'WORK PLACEMENT',
                'TEMPORARY JOB',
                'SUMMER JOB',
                'CAREER DEVELOPMENT',
                'PROFESSIONAL EXPERIENCE',
                'INDUSTRY TRAINING',
                'INTERNSHIP'],
 'MANAGEMENT': ['MANAGEMENT',
                'LEADERSHIP',
                'EXECUTIVE',
                'DIRECTOR',
                'MANAGER',
                'SUPERVISOR',
                'TEAM LEADER',
                'C-LEVEL',
                'CHIEF',
                'HEAD',
                'OFFICER',
                'ADMINISTRATOR',
                'COORDINATOR',
                'CONTROLLER',
                'PRINCIPAL',
                'PRESIDENT',
                'VICE PRESIDENT',
                'GENERAL MANAGER',
                'OPERATIONS MANAGER',
                'PROJECT MANAGER'],
 'MARKETING': ['MARKETING',
               'ADVERTISING',
               'BRAND MANAGEMENT',
               'MARKET RESEARCH',
               'DIGITAL MARKETING',
               'SOCIAL MEDIA',
               'CONTENT CREATION',
               'COPYWRITING',
               'PUBLIC RELATIONS',
               'SALES',
               'CAMPAIGN MANAGEMENT',
               'ANALYTICS',
               'SEO (SEARCH ENGINE OPTIMIZATION)',
               'SEM (SEARCH ENGINE MARKETING)',
               'EMAIL MARKETING',
               'EVENT PLANNING',
               'CUSTOMER ACQUISITION',
               'PRODUCT MANAGEMENT',
               'MARKET SEGMENTATION',
               'MARKETING STRATEGY'],
 'ONLINE SET-UP': ['REMOTE WORK',
                   'VIRTUAL OFFICE',
                   'TELECOMMUTING',
                   'DIGITAL NOMAD',
                   'WORK FROM HOME',
                   'FLEXIBLE WORK',
                   'TELEWORK',
                   'VIRTUAL TEAM',
                   'REMOTE COMMUNICATION',
                   'REMOTE COLLABORATION',
                   'VIRTUAL WORKSPACE',
                   'ONLINE PRODUCTIVITY',
                   'ONLINE PRESENCE'],
 'TECHNOLOGY': ['INFORMATION TECHNOLOGY',
                'TECHNOLOGY',
                'IT',
                'SOFTWARE DEVELOPMENT',
                'PROGRAMMING',
                'WEB DEVELOPMENT',
                'DATABASE MANAGEMENT',
                'NETWORK ADMINISTRATION',
                'CYBERSECURITY',
                'DATA ANALYSIS',
                'SYSTEM ADMINISTRATION',
                'CLOUD COMPUTING',
                'ARTIFICIAL INTELLIGENCE',
                'MACHINE LEARNING',
                'DATA SCIENCE',
                'DEVOPS',
                'UI/UX DESIGN',
                'TECHNICAL SUPPORT',
                'IT CONSULTING',
                'QUALITY ASSURANCE',
                'PROJECT MANAGEMENT'],
'PAID': [
    "PAID",
    "EMPLOYMENT",
    "COMPENSATION",
    "REMUNERATION",
    "SALARY",
    "WAGES",
    "INCOME",
    "EARNINGS",
    "PAYCHECK",
    "PROFIT",
    "RENUMERATION",
    "STIPEND",
    "REMUNERATIVE",
    "MONETARY",
    "BENEFITS",
    "COMMISSION",
    "BONUSES",
    "PER DIEM",
    "HONORARIUM",
    "ALLOWANCE"
],
'HYBRID' : [
    "HYBRID",
    "REMOTE",
    "IN-PERSON",
    "FLEXIBLE",
    "DIGITAL",
    "WORKPLACE",
    "COLLABORATION",
    "COMMUNICATION",
    "OFFICE",
    "VIRTUAL",
    "TEAM",
    "SCHEDULE",
    "MEETINGS",
    "TECHNOLOGY",
    "CONNECTIVITY",
    "ADAPTABILITY",
    "BALANCE",
    "PRODUCTIVITY",
    "EMPLOYEE",
    "ENGAGEMENT"
],
 'ONSITE' : [
    "ONSITE",
    "IN-PERSON",
    "OFFICE",
    "WORKPLACE",
    "COLLABORATION",
    "COMMUNICATION",
    "TEAM",
    "SCHEDULE",
    "MEETINGS",
    "ROUTINE",
    "WORKSPACE",
    "INTERACTION",
    "EQUIPMENT",
    "INFRASTRUCTURE",
    "SAFETY",
    "SECURITY",
    "POLICIES",
    "PROXIMITY",
    "ENVIRONMENT",
    "PRODUCTIVITY"
],
 'FULL-TIME' : [
    "FULL-TIME",
    "CAREER",
    "EMPLOYMENT",
    "PROFESSIONAL",
    "JOB SECURITY",
    "BENEFITS",
    "SALARY",
    "WORKWEEK",
    "VACATION",
    "SICK LEAVE",
    "HEALTH INSURANCE",
    "RETIREMENT",
    "STABILITY",
    "WORK-LIFE BALANCE",
    "PROMOTION",
    "RESPONSIBILITIES",
    "COMMITMENT",
    "PERFORMANCE",
    "OFFICE HOURS",
    "COLLEAGUE"
]
 
}
